### ISSUE TITLE
System.IO.FileNotFoundException: "Input file not found" with Stream

### ISSUE THREAD

**Issue by Feodoros** [rosenbjerg/FFMpegCore#120]
How I can do SnapShot with IMediaAnalysis that was created with Stream?

**Comment by tiesont** [comment]
I'd assume this same code still works: https://github.com/rosenbjerg/FFMpegCore#ffmpeg

If you're having issues with something you wrote, I'd suggest adding an example of what you're doing - hard to troubleshot, otherwise. One thing to watch out for, since you've mentioned Stream in your issue title, to make sure that you haven't disposed the stream before calling `FFMpeg.Snapshot()` with your IMediaAnalysis.

**Comment by Feodoros** [comment]
https://github.com/rosenbjerg/FFMpegCore/issues/71
