### ISSUE TITLE
Cancelling throws FFMpegException instead of TaskCanceledException

### ISSUE THREAD

**Issue by halomakes** [rosenbjerg/FFMpegCore#268]
Awesome library :)

I noticed that when I cancel a transcode process with a CancellationToken, an FFMpegException is thrown instead of the usual TaskCanceledException you would expect to see in this situation.  I know you can disable exceptions by passing a false into the ProcessAsync call but I would still like to get exceptions for other issues that arise.  It would be nice if a TaskCanceledException was thrown so that these could be caught separately like usual.

![image](https://user-images.githubusercontent.com/5904472/138564375-3295bc4e-f4d5-42c6-8f3d-a0090a1aa5fd.png)

**Comment by rosenbjerg** [comment]
I understand why you would expect a TaskCanceledException, but since you cancel without timeout, ffmpeg doesn't have time to stop processing and shut down properly, so exitcode will be non-zero which throws the exception you see,
If there is a practical way to wrap this exception in a TaskCanceledException if thrown during cancellation, I'll implement it

**Comment by BobSilent** [comment]
@rosenbjerg maybe an idea would be
https://github.com/rosenbjerg/FFMpegCore/blob/e052688209335370e8c50bb9056ff9296d612a8c/FFMpegCore/FFMpeg/FFMpegArgumentProcessor.cs#L189-L195

to check if `cancellationToken.IsCancellationRequested` and then return and not `throw`.

**Comment by rosenbjerg** [comment]
Version 4.8 has just been released, and contains fix for this issue :)
