### ISSUE TITLE
Spawn process with lower priority?

### ISSUE THREAD

**Issue by VivianFoxglove** [rosenbjerg/FFMpegCore#338]
When actually running ffmpeg from the command line, I could do

`start /belownormal ffmpeg.exe [params]`

Is there any similar thing I can do with this library?

I'm running from windows servers right now, hence /belownormal as opposed to niceness

**Comment by rosenbjerg** [comment]
Not really, since that is an OS specific thing.
`start` is a Windows program, and this library aims to be cross-platform

**Comment by hermes-del-rondo** [comment]
First of all, thank you very much for this library. It really helps me a lot. I know this issue is quite old, but I could use this feature as well. As I can see, you are using the `Process` class to create the FFmpeg process. It has a property called `PriorityClass` with which you can set the priority of the process (`Idle`, `Normal`, ...). This value could be passed in `FFOptions`, for example. To ensure the default behavior of `Process`, you could set `Process.PriorityClass` only if `FFOptions.Priority != null`.
