### ISSUE TITLE
Snapshot function with latest release is boolean only?

### ISSUE THREAD

**Issue by bitmaps** [rosenbjerg/FFMpegCore#402]
Updated to latest nuget package and the following no longer works as result is now a boolean.

`var bitmap = FFMpeg.Snapshot(inputPath, new Size(200, 400), TimeSpan.FromMinutes(1));`

Is it possible to have the snapshot return a bitmap?

**Comment by rosenbjerg** [comment]
Functionality depending System.Drawing.Common, which is Windows-only now, has been moved to a separate "extension" package to keep the main library properly cross-platform.
[FFMpegCore.Extensions.System.Drawing.Common](https://www.nuget.org/packages/FFMpegCore.Extensions.System.Drawing.Common)
So installing this package should add the extension method you were using previously in version 4.x

#396 which is still a draft PR would add similar extension methods, but using the Skia graphics library instead of System.Drawing.Common
