### ISSUE TITLE
How to using OutputToUrl

### ISSUE THREAD

**Issue by hoan277** [rosenbjerg/FFMpegCore#421]
Hello, i'm try using OutputToUrl to send to Youtube or Facebook rtmp, please help me use OutputToUrl function.
Thank you so much.

**Comment by hqkirkland** [comment]
Your question isn't specific but I came here for help, so I'll offer you some guidance since it took me a while too.

I'd suggest building the .exe command + arguments first before starting implementation.

Here's a snippet from my current project:

```
public static FFMpegArgumentProcessor BroadcastFile(string inputFile, string rtmpEndpoint)
{
    return FFMpegArguments
        .FromFileInput(
            inputFile,
            true,
            inputOptions => inputOptions
                .WithCustomArgument("-re")
        )
        .OutputToUrl(
            "rtmp://10.0.0.20/tvexecnet/K409",
            outOptions => outOptions
                .WithVideoCodec(VideoCodec.LibX264)
                .WithAudioCodec(AudioCodec.Aac)
                .UsingMultithreading(false)
                .WithAudioBitrate(AudioQuality.VeryHigh)
                .WithFastStart()
        );
}
```

`.WithCustomArgument("-re")` - Instructs FFMPEG to read input file at 1x speed (or as close as possible).
`rtmp://10.0.0.20/tvexecnet/K409` is my local RTMP application. I'm guessing your string will be more complex and include a channel key of some sort?

**Comment by rosenbjerg** [comment]
Sorry, I don't have experience with that
