### ISSUE TITLE
In memory snapshot is not available anymore ?

### ISSUE THREAD

**Issue by MidKnightXI** [rosenbjerg/FFMpegCore#490]
I was going through the doc looking for a way to to in memory snapshot and found out I could do:

```csharp
var bitmap = FFMpeg.Snapshot(inputPath, new Size(200, 400), TimeSpan.FromMinutes(1));
```

But after installing the nuget on my project and trying it it says I need an output to use that method and the return type is a `boolean` so it uses the other method that saves the snapshot on the drive.

Is this in-memory snapshot method still available in the nuget package ?

**Comment by MidKnightXI** [comment]
My project is using .NET 7 and I use the 5.1.0 of the nuget

**Comment by tiesont** [comment]
The overload you're referring to is part of an extension: [FFMpegCore.Extensions.System.Drawing.Common/FFMpegImage.cs](https://github.com/rosenbjerg/FFMpegCore/blob/eb221c3e49ce6013b164bad0fc88bf0879da95c3/FFMpegCore.Extensions.System.Drawing.Common/FFMpegImage.cs#L17)

You'll need import that library in order to have access to the overload: https://www.nuget.org/packages/FFMpegCore.Extensions.System.Drawing.Common
