### ISSUE TITLE
Operation not Permitted

### ISSUE THREAD

**Issue by South2AK** [rosenbjerg/FFMpegCore#550]
I´m using ffmpegcore to compress a video in .NET MAUI MAC

On Windows it works fine but on Mac I´m always getting "An error occurred trying to start process '/opt/homebrew/cellar/ffmpeg/7.1_3/bin/ffmpeg' with working directory '/users/s2k/Desktop'. Operation not permitted"

**Comment by tiesont** [comment]
> Operation not permitted

That's macOS telling you that the operation isn't allowed due to _System Integrity Protection_, or SIP, which is more or less the same as User Account Control, or UAC, in Windows userland. 

You might find this Stack Overflow Q&A useful: https://stackoverflow.com/questions/32659348/operation-not-permitted-when-on-root-el-capitan-rootless-disabled

Basically, though, this isn't an issue with FFMpegCore, but a permissions issue with how you're executing your app within the OS.

**Comment by South2AK** [comment]
@tiesont oh okay, Is there any alternative other than disabling sip?

**Comment by tiesont** [comment]
> @tiesont oh okay, Is there any alternative other than disabling sip?

Not really sure. I rarely use an Apple product of any sort. I think one of the answers in the linked question mentions running the application from a different folder - some folders are more restrictive than others on macOS (and pretty much any operating system, to be fair). If it's a console/terminal app, you could probably execute it with super user permissions (`sudo`, basically) but, again, I'm not a Mac user. Sorry.
