### ISSUE TITLE
i don't think your prerequisites are [accurate](https://developer.nvidia.com/ffmpeg).  i think this depends on the input codec.  I'll run some tests but I don't think your software is gpu enabled.

### ISSUE THREAD

**Issue by curlyfro** [rosenbjerg/FFMpegCore#78]
i don't think your prerequisites are [accurate](https://developer.nvidia.com/ffmpeg).  i think this depends on the input codec.  I'll run some tests but I don't think your software is gpu enabled.

_Originally posted by @curlyfro in https://github.com/rosenbjerg/FFMpegCore/issues/77#issuecomment-648101634_

**Comment by curlyfro** [comment]
i just tested.   i executed against this input file and it was 90% GPU.  when I ran the same file against your wrapper, the GPU was 15%.

ffmpeg -vsync 0 -hwaccel cuvid -c:v h264_cuvid -i "input.mp4" -vf "hwupload_cuda" -c:v h264_nvenc output.mp4

**Comment by rosenbjerg** [comment]
No of course not, that command explicitly specifies hwaccel and uses both h264_cuvid and h264_nvenc  video codecs instead of the "regular" h264 codecs used by this wrapper when specifying that codec. .WithVideoCodec("h264_nvenc") also 
You can only supply those using .WithCustomArgument(..), but the majority.

We don't claim to support this, and until someone sees the need in implementing it, it won't be supported

**Comment by curlyfro** [comment]
ok -- thanks
